
```{r}
rm(list=ls())
setwd("C:/Users/Lenovo/Code/R/sparse-convex-clustering/scvxclustr/example")
set.seed(123)

# Load scvxclustr package
library(devtools)
library(scvxclustr)

# load necessary functions
source("util.R")


```


```{r}

n = 60          # Sample size
true_p = 20     # Number of true features
p = 80        # Number of total features (p = 150, 500)
k = 4           # Number of true cluster
mu = 1.2        # mean of normal distribution (mu = 0.6, 0.9)
sigma = 1       # sd of normal distribution
method = "ama"  # Fitted method (method = "ama", "admm")

# Simiulate 4 cluster Gaussian data
data <- simu_4(n = n, true_p = true_p, p = p, k = k, mu = mu, sigma = sigma )
```

```{r}
#standardize n by p data matrix
X <- scale(data$X,center=TRUE,scale=FALSE)
```

```{r}
# Validation data
data_valide <- list()
for(i in 1:5){
  data_valide[[i]] <- simu_4(n = n, true_p = true_p, p = p, k = k, mu = mu, sigma = sigma )
}
```


```{r}
# Adaptive Weight (if possible)
g1 <-6
g2 <- 0
Gamma2.weight <- c(rep(0.5, true_p), rep(1,p - true_p) )
k_w <- 5    # Number of nearest neighbors
phi <- 0.5  # scale of the kernel
verbose <- TRUE # show more information
w <- dist_weight( t(X) / sqrt(p),phi, dist.type = "euclidean", p = 2 )
w <- knn_weights(w,k = k_w,n)
nu <- AMA_step_size(w,n) /2
```

```{r}
## Validate the cvxclust and scvxclust is the same when g2 = 0
# Fit a convex clustering model
fit1 <- cvxclust(X = t(X), w = w, gamma = g1, method = "ama", nu = nu, max_iter = 10000, tol = 1e-5)
```

```{r}
# Fit a sparce convex clsutering model
fit2 <- scvxclust(X = X, w = w, Gamma1 = g1, Gamma2 = g2, Gamma2_weight = Gamma2.weight, method = method, nu = nu, max_iter = 10000, tol_abs = 1e-5)
```

```{r}
g1 <- 9
g2 <- 10
fit3 <- scvxclust(X = X, w = w, Gamma1 = g1, Gamma2 = g2, Gamma2_weight = Gamma2.weight, method = method, nu = nu, max_iter = 10000, tol_abs = 1e-5)
```

```{r}
write.csv(t(X),file = 'X.csv')
```

```{r}
write.csv(fit1$U[[1]],file = 'fit1.csv')
```

```{r}
write.csv(t(fit2$U[[1]]),file = 'fit2.csv')
```

```{r}
write.csv(t(fit3$U[[1]]),file = 'fit3.csv')
```

```{r}
#稀疏凸聚类和凸聚类的效果对比(g2=0时)几乎一致
diff_U <- as.numeric(fit1$U[[1]] - t(fit2$U[[1]]) )
summary( diff_U )
plot(diff_U)
```

```{r}
## Validate the sparse convex clustring model create a correct clustering structure under the toy exmaple.
g1 <- 9
g2 <- 10
fit_predict <- fit_sparse(X = X, gamma1 = g1, gamma2 = g2, Gamma2.weight, k_w, phi, method = method, data_valide = data_valide, verbose = F)

```

```{r}
fit_predict$predict
```

```{r}
table(data$label, fit_predict$cluster[[1]])
```


```{r}
write.csv(t(fit_predict$U[[1]]),file = 'fit-pred.csv')
```

